### ISSUE TITLE
Go to selected date

### ISSUE THREAD

**Issue by jazzn3rd** [nheath99/NodaTimePicker#92]
I would like a function that i could call to go to the right month for selected date.

**Comment by nheath99** [comment]
Hi @jazzn3rd, can you give more details please? From my understanding on the DatePicker/DateTimePicker when ViewMode == Days you want to be able to set the MonthToDisplay property?

There is already an internal mechanism to do this, but I can expose this as a public method if it's required.

**Comment by julienGrd** [comment]
@nheath99 : It seem this functionnality is broken. 
On your demo (https://nodatimepicker.z13.web.core.windows.net/), part Set Selected Date Programatically
When you click on the last button "Set Date to monday 6 January" which was supposed to change month, the month not changed.

It's strange because the today works and change month correctly

do you reproduce?

**Comment by julienGrd** [comment]
Hello, any chance to have this issue solve one day ?
